import type { HipEvent, UserSubmission, NGO } from "@/types";
import type { Zone, Boundary } from "@/types/zone";
import {
  DARFUR_BORDER,
  KHARTOUM_STATE_BORDER,
  EL_FASHER_SIEGE,
  EL_GENEINA_ZONE,
  GEZIRA_STATE_BORDER,
  KORDOFAN_CORRIDOR,
  PORT_SUDAN_CORRIDOR,
} from "@/lib/sudan-zones";

export const PLACEHOLDER_USER = {
  id: "USR-001",
  name: "Sarah Chen",
  email: "sarah.chen@msf.org",
  organisation: "MSF",
  role: "analyst" as const,
  ngo_id: "NGO-001",
  avatar_initials: "SC",
};

export const PLACEHOLDER_EVENTS: HipEvent[] = [
  {
    id: "EVT-0042",
    ontology_class: "armed_conflict",
    severity: "critical",
    lat: 15.5,
    lng: 32.56,
    region_id: "REG-002",
    location_name: "Khartoum, Sudan",
    timestamp: "2024-11-15T06:32:00Z",
    description:
      "RSF advances on SAF positions in Bahri district. Heavy artillery and airstrikes reported.",
    source_type: "drone",
    source_label: "DRN-001",
    confidence_score: 0.94,
    verification_status: "verified",
    verified_by: "ANA-007",
    assigned_ngo_ids: ["NGO-002"],
    related_event_ids: ["EVT-0038"],
    last_updated: "2024-11-15T06:45:00Z",
  },
  {
    id: "EVT-0038",
    ontology_class: "displacement_mass",
    severity: "critical",
    lat: 13.63,
    lng: 25.35,
    region_id: "REG-001",
    location_name: "El Fasher, North Darfur",
    timestamp: "2024-11-14T14:10:00Z",
    description:
      "RSF siege intensifies. 50,000+ civilians trapped. Hospital struck by shelling.",
    source_type: "satellite",
    source_label: "Satellite Pass 2024-11-14",
    confidence_score: 0.91,
    verification_status: "verified",
    verified_by: "ANA-003",
    assigned_ngo_ids: ["NGO-001", "NGO-003"],
    related_event_ids: ["EVT-0042"],
    last_updated: "2024-11-14T15:00:00Z",
  },
  {
    id: "EVT-0051",
    ontology_class: "bridge_damaged",
    severity: "high",
    lat: 15.65,
    lng: 32.48,
    region_id: "REG-002",
    location_name: "Omdurman Bridge, Khartoum",
    timestamp: "2024-11-15T09:15:00Z",
    description:
      "Last functioning Nile bridge crossing destroyed by airstrikes. Khartoum effectively bisected.",
    source_type: "satellite",
    source_label: "Satellite Pass 2024-11-15",
    confidence_score: 0.88,
    verification_status: "verified",
    verified_by: "ANA-005",
    assigned_ngo_ids: ["NGO-002"],
    related_event_ids: [],
    last_updated: "2024-11-15T09:15:00Z",
  },
  {
    id: "EVT-0055",
    ontology_class: "aid_obstruction",
    severity: "high",
    lat: 14.4,
    lng: 33.52,
    region_id: "REG-003",
    location_name: "Wad Medani, Gezira State",
    timestamp: "2024-11-15T11:40:00Z",
    description:
      "RSF looting of WFP food warehouses. All humanitarian operations suspended.",
    source_type: "analyst_input",
    source_label: "ANA-003",
    confidence_score: 0.82,
    verification_status: "verified",
    verified_by: "ANA-003",
    assigned_ngo_ids: ["NGO-002"],
    related_event_ids: [],
    last_updated: "2024-11-15T11:40:00Z",
  },
  {
    id: "EVT-0060",
    ontology_class: "disease_outbreak",
    severity: "medium",
    lat: 13.45,
    lng: 22.44,
    region_id: "REG-001",
    location_name: "El Geneina, West Darfur",
    timestamp: "2024-11-13T08:00:00Z",
    description:
      "Cholera outbreak among displaced populations. 200+ cases. No medical infrastructure.",
    source_type: "news_agent",
    source_label: "Reuters",
    confidence_score: 0.72,
    verification_status: "verified",
    verified_by: "ANA-011",
    assigned_ngo_ids: ["NGO-001"],
    related_event_ids: [],
    last_updated: "2024-11-13T10:00:00Z",
  },
];

export const PLACEHOLDER_SUBMISSIONS: UserSubmission[] = [
  {
    id: "RPT-20241115-0847",
    submitter_id: "USR-IND-001",
    is_anonymous: false,
    ontology_class_suggested: "aid_obstruction",
    severity_suggested: "high",
    lat: 14.4,
    lng: 33.52,
    region_id: "REG-003",
    description:
      "RSF soldiers looting food warehouse in Wad Medani. Civilians fleeing south.",
    submitted_at: "2024-11-15T11:03:00Z",
    status: "pending",
    helios_confidence: 0.61,
    helios_similar_event_id: "EVT-0055",
  },
  {
    id: "RPT-20241114-1630",
    submitter_id: "USR-IND-003",
    is_anonymous: false,
    ontology_class_suggested: "water_contamination",
    severity_suggested: "medium",
    lat: 13.45,
    lng: 22.44,
    region_id: "REG-001",
    description:
      "No clean water in El Geneina camp. Many children sick with diarrhoea.",
    submitted_at: "2024-11-14T16:30:00Z",
    status: "verified",
    reviewed_by: "ANA-011",
    linked_event_id: "EVT-0060",
    helios_confidence: 0.88,
  },
];

export const PLACEHOLDER_ZONES: Zone[] = [
  {
    id: "ZON-001",
    zone_type: "conflict_zone",
    name: "Active Conflict — Greater Darfur",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [DARFUR_BORDER] } },
    risk_score: 96,
    confidence_score: 0.92,
    source_type: "analyst_input",
    last_updated: "2024-11-15T06:00:00Z",
  },
  {
    id: "ZON-002",
    zone_type: "conflict_zone",
    name: "Active Conflict — Khartoum State",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [KHARTOUM_STATE_BORDER] } },
    risk_score: 94,
    confidence_score: 0.95,
    source_type: "analyst_input",
    last_updated: "2024-11-15T06:00:00Z",
  },
  {
    id: "ZON-003",
    zone_type: "no_go_zone",
    name: "No-Go — El Fasher Siege Zone",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [EL_FASHER_SIEGE] } },
    risk_score: 98,
    confidence_score: 0.95,
    source_type: "satellite",
    last_updated: "2024-11-15T00:00:00Z",
  },
  {
    id: "ZON-004",
    zone_type: "no_go_zone",
    name: "No-Go — El Geneina (Destroyed)",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [EL_GENEINA_ZONE] } },
    risk_score: 99,
    confidence_score: 0.98,
    source_type: "analyst_input",
    last_updated: "2024-11-15T00:00:00Z",
  },
  {
    id: "ZON-005",
    zone_type: "contested_territory",
    name: "Contested — Gezira State (RSF-held)",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [GEZIRA_STATE_BORDER] } },
    risk_score: 82,
    confidence_score: 0.88,
    source_type: "satellite",
    last_updated: "2024-11-14T16:00:00Z",
  },
  {
    id: "ZON-006",
    zone_type: "contested_territory",
    name: "Contested — Kordofan Corridor",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [KORDOFAN_CORRIDOR] } },
    risk_score: 72,
    confidence_score: 0.75,
    source_type: "analyst_input",
    last_updated: "2024-11-14T12:00:00Z",
  },
  {
    id: "ZON-007",
    zone_type: "safe_zone",
    name: "Safe Zone — Port Sudan Corridor",
    geojson: { type: "Feature", properties: {}, geometry: { type: "Polygon", coordinates: [PORT_SUDAN_CORRIDOR] } },
    risk_score: 15,
    controlling_entity: "SAF / Government of Sudan",
    confidence_score: 0.91,
    source_type: "analyst_input",
    last_updated: "2024-11-15T07:00:00Z",
  },
];

export const PLACEHOLDER_BOUNDARIES: Boundary[] = [
  {
    id: "BND-001",
    boundary_type: "frontline_active",
    name: "Khartoum Frontline — SAF vs RSF",
    geojson: {
      type: "Feature",
      properties: {},
      geometry: {
        type: "LineString",
        coordinates: [
          [32.3, 15.7],
          [32.45, 15.62],
          [32.55, 15.58],
          [32.7, 15.55],
          [32.85, 15.5],
        ],
      },
    },
    advance_direction: 180,
    confidence_score: 0.88,
    last_updated: "2024-11-15T05:00:00Z",
  },
  {
    id: "BND-002",
    boundary_type: "frontline_active",
    name: "El Fasher Siege Perimeter",
    geojson: {
      type: "Feature",
      properties: {},
      geometry: {
        type: "LineString",
        coordinates: [
          [25.0, 13.9],
          [25.2, 13.75],
          [25.5, 13.7],
          [25.8, 13.8],
          [25.95, 14.0],
        ],
      },
    },
    advance_direction: 0,
    confidence_score: 0.82,
    last_updated: "2024-11-15T05:00:00Z",
  },
  {
    id: "BND-003",
    boundary_type: "disputed_border",
    name: "RSF / SAF Control Line — Kordofan",
    geojson: {
      type: "Feature",
      properties: {},
      geometry: {
        type: "LineString",
        coordinates: [
          [29.0, 13.5],
          [30.0, 14.0],
          [31.0, 14.5],
          [31.5, 15.0],
        ],
      },
    },
    confidence_score: 0.65,
    last_updated: "2024-11-12T00:00:00Z",
  },
];

export const PLACEHOLDER_NGOS: NGO[] = [
  {
    id: "NGO-001",
    name: "MSF",
    abbreviation: "MSF",
    zone_name: "Greater Darfur",
    colour: "#00D4FF",
    zone_geojson: {
      type: "Feature",
      properties: { id: "NGO-001", name: "Greater Darfur" },
      geometry: { type: "Polygon", coordinates: [DARFUR_BORDER] },
    },
  },
  {
    id: "NGO-002",
    name: "OCHA",
    abbreviation: "OCHA",
    zone_name: "Khartoum / Gezira",
    colour: "#7B61FF",
    zone_geojson: {
      type: "Feature",
      properties: { id: "NGO-002", name: "Khartoum / Gezira" },
      geometry: { type: "Polygon", coordinates: [KHARTOUM_STATE_BORDER] },
    },
  },
  {
    id: "NGO-003",
    name: "UNHCR",
    abbreviation: "UNHCR",
    zone_name: "El Fasher Operations",
    colour: "#00FF88",
    zone_geojson: {
      type: "Feature",
      properties: { id: "NGO-003", name: "El Fasher Operations" },
      geometry: { type: "Polygon", coordinates: [EL_FASHER_SIEGE] },
    },
  },
  {
    id: "NGO-004",
    name: "ICRC",
    abbreviation: "ICRC",
    zone_name: "Kordofan Corridor",
    colour: "#FF9500",
    zone_geojson: {
      type: "Feature",
      properties: { id: "NGO-004", name: "Kordofan Corridor" },
      geometry: { type: "Polygon", coordinates: [KORDOFAN_CORRIDOR] },
    },
  },
  {
    id: "NGO-005",
    name: "WFP",
    abbreviation: "WFP",
    zone_name: "Port Sudan Hub",
    colour: "#FF6B35",
    zone_geojson: {
      type: "Feature",
      properties: { id: "NGO-005", name: "Port Sudan Hub" },
      geometry: { type: "Polygon", coordinates: [PORT_SUDAN_CORRIDOR] },
    },
  },
];
